In [5]:
## Concatenate ##

import numpy as np
ar1=np.array([7,8,3,4,5,5])
ar2=np.array([4,5,6,8,6,7])

at=np.concatenate((ar1,ar2))
at

array([7, 8, 3, 4, 5, 5, 4, 5, 6, 8, 6, 7])

In [2]:
import numpy as np
ar=np.array([34,12,34,54,12,43])
print(ar[3]+ar[5])

97


In [8]:
import numpy as np
ar1=np.array([2,4,5,6,6,7,8,9])
ar2=np.array([9,8,7,6,10,11,12,13])
print(ar1.ndim)
print(ar2.ndim)

atp=np.concatenate((ar1,ar2))
atp

1
1


array([ 2,  4,  5,  6,  6,  7,  8,  9,  9,  8,  7,  6, 10, 11, 12, 13])

In [9]:
import numpy as np
ar2=np.array([[22,23,24],[25,62,72]])
ar3=np.array([[222,223,242],[225,622,722]])
at=np.concatenate((ar2,ar3))
at

array([[ 22,  23,  24],
       [ 25,  62,  72],
       [222, 223, 242],
       [225, 622, 722]])

In [10]:
import numpy as np
ar2=np.array([[22,23,24],[25,62,72]])
ar3=np.array([[222,223,242],[225,622,722]])
ar4=np.array([[32,22,24],[2,62,72]])

at1=np.concatenate((ar2,ar3,ar4),axis=1)   ## (Axis 1=Converts rows into column) ##
print(at1)

[[ 22  23  24 222 223 242  32  22  24]
 [ 25  62  72 225 622 722   2  62  72]]


In [11]:
## Split Function ##

import numpy as np
ar1=np.array([3,4,5,6,7,8,9,4])
ap=np.array_split(ar1,3)
print(ap)

[array([3, 4, 5]), array([6, 7, 8]), array([9, 4])]


In [12]:
import numpy as np
ar1=np.array([3,4,5,6,7,8,9,4])
ap=np.array_split(ar1,6)
print(ap)

[array([3, 4]), array([5, 6]), array([7]), array([8]), array([9]), array([4])]


In [13]:
import numpy as np
ar1=np.array([3,4,5,6,7,8,9,4])
ap=np.array_split(ar1,8)
print(ap)

[array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([4])]


In [14]:
import numpy as np
ar1=np.array([3,4,5,6,7,8,9,4])
ap=np.array_split(ar1,10)
print(ap)

[array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([4]), array([], dtype=int32), array([], dtype=int32)]


In [17]:
## Where ##(Where function used to indicate array position)

import numpy as np
ar1=np.array([23,34,45,32,44,12,32,55,67])
ap=np.where(ar1==32)
print(ap)

(array([3, 6], dtype=int64),)


In [19]:
import numpy as np
ar2=np.array([22,23,24,25,62,72])
ap=np.where(ar2%2==0)       ## Check even numbers array position ##
print(ap)

(array([0, 2, 4, 5], dtype=int64),)


In [20]:
import numpy as np
ar2=np.array([22,23,24,25,62,72])
ap=np.where(ar2%2==1)    ## Check odd numbers array position ##
print(ap)

(array([1, 3], dtype=int64),)
