In [1]:
import numpy as np

ar1=np.array([2,3,4,5,6,7,8,9])
print(ar1)

[2 3 4 5 6 7 8 9]


In [3]:
print(ar1[0])
print(ar1[-2])

2
8


In [5]:
import numpy as np

ap=np.array([43,45,65,78,90,34,56,78,78])
print([ap])
print(ap[:-4])

[array([43, 45, 65, 78, 90, 34, 56, 78, 78])]
[43 45 65 78 90]


In [6]:
import numpy as np

ap=np.array([43,45,65,78,90,34,56,78,78])
print([ap])

print(ap[-6:-3])

[array([43, 45, 65, 78, 90, 34, 56, 78, 78])]
[78 90 34]


In [7]:
print(ap[-3:-8])

[]


In [9]:
print(ap[5:-4])

[]


In [11]:
print(ap[-4:3])

[]


In [13]:
## Shape ##
ar1=np.array([[2,3,4,5],[6,7,8,9]])
ar1.shape

(2, 4)

In [2]:
## Split ##
import numpy as np
ar2=np.array([22,23,24,25,62,72])
ap=np.array_split(ar2,3)
print(ap)

[array([22, 23]), array([24, 25]), array([62, 72])]


In [5]:
## check array dimension using ndim function ##
import numpy as np
ar1=np.array([[[2,3,4,5],[22,23,24,34],[3,4,5,6],[6,9,7,8],[11,12,13,14],[34,56,45,65]]])
print(ar1.ndim)

3


In [6]:
import numpy as ac
ar2=ac.array([2,4,5,3,5,6,7,8,9])
print(ar2.ndim)

1


In [7]:
## Shape ##
import numpy as np
ar1=np.array([2,4,6,7,8,9,10,34,54])
ar1.shape

(9,)

output:
1 dimenson array indicates only columns

In [11]:
import numpy as np
ar1=np.array([[4,6,7,8],[9,10,34,54]])
ar1.shape

## Output ##
#(2=Rows,4=Columns)#

(2, 4)

In [9]:
import numpy as np
ar1=np.array([[[2,3,4,5],[22,23,24,34],[3,4,5,6],[6,9,7,8],[11,12,13,14],[34,56,45,65]]])
print(ar1.ndim)
ar1.shape                      

## Output ##
#(1=Array,6=Rows,4=Columns)#

3


(1, 6, 4)

In [2]:
## Reshape (Change the dimension of array) ##

import numpy as ac
ar1=ac.array([65,77,45,67,34,56,23,45])
ar1.reshape(4,2)           ##(4=Rows,2=Columns)##

array([[65, 77],
       [45, 67],
       [34, 56],
       [23, 45]])

In [16]:
import numpy as ac
ar1=ac.array([65,77,45,67,34,56,23,45])
ar1.reshape(2,4)    ##(2=Rows,4=Columns)##

array([[65, 77, 45, 67],
       [34, 56, 23, 45]])

In [2]:
import numpy as ab
ar3=ab.array([5,6,7,8,9,4,5,3,34,56,23,67])
atp=ar3.reshape(2,3,2) ##(2=Array Dimension,3=Rows,2=Columns)##     
print(atp)

[[[ 5  6]
  [ 7  8]
  [ 9  4]]

 [[ 5  3]
  [34 56]
  [23 67]]]


In [3]:
import numpy as np
ar1=np.array([2,3,4,5,6,7,8,9,32,11,22,111])
for x in ar1:
    print(x)
    print("---------------------------")
    for y in range(x):
        print(y)
        print(".................................")
        if y == 5:
            print("I am Rahul..")

2
---------------------------
0
.................................
1
.................................
3
---------------------------
0
.................................
1
.................................
2
.................................
4
---------------------------
0
.................................
1
.................................
2
.................................
3
.................................
5
---------------------------
0
.................................
1
.................................
2
.................................
3
.................................
4
.................................
6
---------------------------
0
.................................
1
.................................
2
.................................
3
.................................
4
.................................
5
.................................
I am Rahul..
7
---------------------------
0
.................................
1
.................................
2
.............